name: Kanban Task
description: Crear una tarea para el tablero Kanban del proyecto
title: "[TASK] "
labels: ["kanban"]
body:
  - type: textarea
    id: description
    attributes:
      label: 📌 Descripción
      description: Explica brevemente qué se debe hacer en esta tarea.
      placeholder: Ej. Implementar formulario de registro en React con validación de contraseña.
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: 🧑‍💻 Rol asignado
      options:
        - UX/UI
        - Frontend
        - Backend
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🚦 Prioridad
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Criterios de aceptación
      description: Lista de condiciones que deben cumplirse para dar esta tarea por terminada.
      placeholder: |
        - Validar formato de email y contraseñas seguras
        - Responder 201 con userId al crear usuario
        - Mostrar mensajes de error accesibles en frontend
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: 📝 Notas técnicas / Librerías
      description: Agrega detalles técnicos, librerías a usar o referencias.
      placeholder: |
        - React Hook Form + Zod
        - JWT con expiración + refresh token
        - Prisma migrations en PostgreSQL
    validations:
      required: false
